---
# .github/workflows/rpm-build.yml

name: Build RPM Artifacts

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build_rpm:
    runs-on: ubuntu-latest
    container: 
      image: fedora:latest
      options: --user root

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Build Dependencies
        run: |
          dnf install -y rpm-build python3-pyyaml tar gzip findutils git
      
      - name: Make Build Script Executable
        run: chmod +x build_rpm.sh

      - name: Run RPM Build Script
        run: ./build_rpm.sh

      - name: Commit and Push RPM to Branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add RPMS/*.rpm
          git commit -m "Feat: Add new RPM release for ${{ github.ref_name }}"
          git push
...
